; 管理TUI配置
ALLOW_WRITE=1 ; 允许写操作
ALLOW_DANGER=1 ; 允许危险操作
CHECK_PASSWORD=1 ; 启用数据库密码检查

[DATABASE]
host="localhost"
port=5432
usr="ds4viz_admin"
pwd="ds4vizPwD4A_D_M_I_N!"
prod_db="ds4viz_prod"
test_db="ds4viz_test"
