; 管理TUI配置

PWD="0000"
ALLOW_WRITE=1

[DATABASE]
host="localhost"
port=5432
username="ds4viz_admin"
password="ds4vizPwD4A_D_M_I_N!"
prod_db="ds4viz_prod"
test_db="ds4viz_test"

[SERVER_CONFIG]
path="../src/config/"
